from Attributes import *
from Student import Prediction


class Student:
    # def __init__(self):
    #     self.school = School.School()
    #     self.sex = Sex.Sex()
    #     self.age = Age.Age()
    #     self.address = Address.Address()
    #     self.famsize = Famsize.Famsize()
    #     self.pstatus = Pstatus.Pstatus()
    #     self.medu = Medu.Medu()
    #     self.fedu = Fedu.Fedu()
    #     self.mjob = Mjob.Mjob()
    #     self.fjob = Fjob.Fjob()
    #     self.reason = Reason.Reason()
    #     self.guardian = Guardian.Guardian()
    #     self.traveltime = Traveltime.Traveltime()
    #     self.studytime = Studytime.Studytime()
    #     self.failures = Failures.Failures()
    #     self.schoolsup = Schoolsup.Schoolsup()
    #     self.famsup = Famsup.Famsup()
    #     self.paid = Paid.Paid()
    #     self.activities = Acitivities.Acitivities()
    #     self.nursery = Nursery.Nursery()
    #     self.higher = Higher.Higher()
    #     self.internet = Internet.Internet()
    #     self.romantic = Romantic.Romantic()
    #     self.famrel = Famrel.Famrel()
    #     self.freetime = Freetime.Freetime()
    #     self.goout = Goout.Goout()
    #     self.dalc = Dalc.Dalc()
    #     self.walc = Walc.Walc()
    #     self.health = Health.Health()
    #     self.absences = Absences.Absences()
    #
    #     self.g1 = G1.G1()
    #     self.g2 = G2.G2()
    #     self.g3 = G3.G3()
    #
    #     self.prediction = G3.G3()

    def __init__(self, row):
        self.school = School.School.read_school(row[0])
        self.sex = Sex.Sex.read_sex(row[1])
        self.age = Age.Age.read_age(row[2])
        self.address = Address.Address.read_address(row[3])
        self.famsize = Famsize.Famsize.read_famsize(row[4])
        self.pstatus = Pstatus.Pstatus.read_pstatus(row[5])
        self.medu = Medu.Medu.read_medu(row[6])
        self.fedu = Fedu.Fedu.read_fedu(row[7])
        self.mjob = Mjob.Mjob.read_mjob(row[8])
        self.fjob = Fjob.Fjob.read_fjob(row[9])
        self.reason = Reason.Reason.read_reason(row[10])
        self.guardian = Guardian.Guardian.read_guardian(row[11])
        self.traveltime = Traveltime.Traveltime.read_traveltime(row[12])
        self.studytime = Studytime.Studytime.read_studytime(row[13])
        self.failures = Failures.Failures.read_failures(row[14])
        self.schoolsup = Schoolsup.Schoolsup.read_schoolsup(row[15])
        self.famsup = Famsup.Famsup.read_famsup(row[16])
        self.paid = Paid.Paid.read_paid(row[17])
        self.activities = Activities.Activities.read_activities(row[18])
        self.nursery = Nursery.Nursery.read_nursery(row[19])
        self.higher = Higher.Higher.read_higher(row[20])
        self.internet = Internet.Internet.read_internet(row[21])
        self.romantic = Romantic.Romantic.read_romantic(row[22])
        self.famrel = Famrel.Famrel.read_famrel(row[23])
        self.freetime = Freetime.Freetime.read_freetime(row[24])
        self.goout = Goout.Goout.read_goout(row[25])
        self.dalc = Dalc.Dalc.read_dalc(row[26])
        self.walc = Walc.Walc.read_walc(row[27])
        self.health = Health.Health.read_health(row[28])
        self.absences = Absences.Absences.read_absences(row[29])
        self.g1 = G1.G1.read_g1(row[30])
        self.g2 = G2.G2.read_g2(row[31])
        self.g3 = G3.G3.read_g3(row[32])

        self.prediction = Prediction.Prediction()
